import { sponsorships, servers } from '@/lib/db'

/** Shared select fields for sponsorship+server join queries. */
export const sponsorshipServerSelect = {
  id: sponsorships.id,
  serverId: sponsorships.serverId,
  sponsorName: sponsorships.sponsorName,
  sponsorUrl: sponsorships.sponsorUrl,
  sponsorLogo: sponsorships.sponsorLogo,
  startDate: sponsorships.startDate,
  endDate: sponsorships.endDate,
  amount: sponsorships.amount,
  currency: sponsorships.currency,
  notes: sponsorships.notes,
  active: sponsorships.active,
  createdAt: sponsorships.createdAt,
  updatedAt: sponsorships.updatedAt,
  serverIdCol: servers.id,
  serverName: servers.name,
  serverDescription: servers.description,
  serverOwner: servers.owner,
  serverRepo: servers.repo,
  serverFullSlug: servers.fullSlug,
  serverCategory: servers.category,
  serverIsOfficial: servers.isOfficial,
  serverIsSponsored: servers.isSponsored,
  serverGithubUrl: servers.githubUrl,
  serverTags: servers.tags,
  serverIsRemote: servers.isRemote,
  serverAuthType: servers.authType,
  serverEndpoint: servers.endpoint,
  serverFeatured: servers.featured,
  serverFeaturedUntil: servers.featuredUntil,
  serverSponsoredUntil: servers.sponsoredUntil,
  serverStars: servers.stars,
  serverForks: servers.forks,
  serverAuthorId: servers.authorId,
  serverCreatedAt: servers.createdAt,
  serverUpdatedAt: servers.updatedAt,
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function mapSponsorshipRow(r: any) {
  return {
    id: r.id,
    serverId: r.serverId,
    sponsorName: r.sponsorName,
    sponsorUrl: r.sponsorUrl,
    sponsorLogo: r.sponsorLogo,
    startDate: r.startDate,
    endDate: r.endDate,
    amount: r.amount,
    currency: r.currency,
    notes: r.notes,
    active: r.active,
    createdAt: r.createdAt,
    updatedAt: r.updatedAt,
    server: {
      id: r.serverIdCol,
      name: r.serverName,
      description: r.serverDescription,
      owner: r.serverOwner,
      repo: r.serverRepo,
      fullSlug: r.serverFullSlug,
      category: r.serverCategory,
      isOfficial: r.serverIsOfficial,
      isSponsored: r.serverIsSponsored,
      githubUrl: r.serverGithubUrl,
      tags: r.serverTags,
      isRemote: r.serverIsRemote,
      authType: r.serverAuthType,
      endpoint: r.serverEndpoint,
      featured: r.serverFeatured,
      featuredUntil: r.serverFeaturedUntil,
      sponsoredUntil: r.serverSponsoredUntil,
      stars: r.serverStars,
      forks: r.serverForks,
      authorId: r.serverAuthorId,
      createdAt: r.serverCreatedAt,
      updatedAt: r.serverUpdatedAt,
    },
  }
}
